substitutions:
  name: atom-echo-office
  friendly_name: Office Echo

packages:
  voice_assistant:
    url: https://github.com/esphome/wake-word-voice-assistants
    file: m5stack-atom-echo/m5stack-atom-echo.yaml
    ref: main

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
